site_url:
  name: Site Url (avec un "/" à la fin)
  default: http://localhost:3000/
  type: string

use_helpdesk_chat:
  name: Activer la messagerie instantannée de support
  default: true
  type: boolean

anonymous_helpdesk_chat:
  name: Activer la messagerie instantannée de support même si l'utilisateur n'est pas connecté
  default: true
  type: boolean
  
legacy_auth_enabled:
  name: "Afficher la page d'authentification interne aux utilisateur"
  default: true
  type: boolean

max_actives_era:
  name: Nombre max de redirections actives 
  default: 2
  type: integer

main_mail_domain:
  name: Domaine de l'adresse principale
  default: gadz.org
default_mail_domains:
  name: Domaines pour lequels les adresses mails sont créée par défaut lors de l'inscrption. Il n'est pas necessaire de spécifier les alias de domaine (voir admin/domaines). Cette liste dois contenir le "main_mail_domains". Domaines séparés par les espaces.
  default: gadz.org m4am.net
default_google_apps_domain_alias:
  name: Domaine google apps par défaut
  default: gadz.fr
availables_google_apps_domain:
  name: Domaine google apps pour lesquels il est possible de créer un adresse. Domaines séparés par les espaces.
  default: gadz.org agoram.org

maintenance_mode:
  name: Mode maintenance
  default: false
  type: boolean

allowed_uuid_in_maintenance_mode:
  name: UUID autorisés à se connecter en mode maintenance ( séparés par un espace )
  type: string


maintenance_message:
  name: Message maintenance
  default: Le site n'est pas encore ouvert, reviens à partir du 8 octobre :-)

moncompte_url:
  name: URL de moncompte.gadz.org ( avec un "/" à la fin )
  default: https://moncompte.gadz.org/